NodeName = "iRainEndpointDev"
RpcAddress = "0.0.0.0:5570"
Broadcast = false

# 艾润主板配置参数
[BoardOptions]
  controllerId = 1
  doorCount = 2

# Socket客户端配置参数
[SocketClientOptions]
  remoteAddress = "192.168.1.107:5000"
  network = "udp"
  readTimeout = "1s"
  writeTimeout = "1s"
  reconnectDelay = "1s"
  keepAlive = true
  keepAliveInterval = "10s"