Name = "iRainTrigger"
Topic = "irain/events"

# 主板配置参数
[BoardOptions]
  controllerId = 1
  scanPeriod = "1s"

# Socket配置参数
[SocketClientOptions]
  remoteAddress = "tcp://192.168.1.125:5000"
  bufferSize = 512
  readTimeout = "1s"
  writeTimeout = "1s"
  autoReconnect = true
  reconnectInterval = "3s"
  keepAlive = true
  keepAliveInterval = "3s"