NodeName = "iRainTriggerDev"
Topic = "irain/events"

# 主板配置参数
[BoardOptions]
  controllerId = 1

# Socket配置参数
[SocketClientOptions]
  remoteAddress = "192.168.1.107:5000"
  network = "tcp"
  readTimeout = "1s"
  writeTimeout = "1s"
  reconnectDelay = "1s"
  keepAlive = true
  keepAliveInterval = "10s"